#!/usr/bin/env python3
"""Build a glyph-fingerprint → char map for the 86Box text-mode decoder.

Renders the standard VGA 8x16 BIOS font (codepage 437) using PIL and the
DejaVu mono fallback if the real BIOS font isn't available. For each
character code 0..255, draws an 8x16 (or 9x16) glyph on black, fingerprints
it the same way `screen.py` does, and writes the table to fontmap.py.

For best fidelity with 86Box's actual VGA output we should fingerprint
glyphs against a screenshot of the real running emulator showing a known
calibration pattern. That's a follow-up; this initial map gets us 80%+ of
character recognition for ASCII.

Usage:
    build-fontmap.py [--out fontmap.py] [--cell 8x16]
"""
from __future__ import annotations
import argparse
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

CP437_TO_UNI = (
    " ☺☻♥♦♣♠•◘○◙♂♀♪♫☼"
    "►◄↕‼¶§▬↨↑↓→←∟↔▲▼"
    " !\"#$%&'()*+,-./"
    "0123456789:;<=>?"
    "@ABCDEFGHIJKLMNO"
    "PQRSTUVWXYZ[\\]^_"
    "`abcdefghijklmno"
    "pqrstuvwxyz{|}~⌂"
    "ÇüéâäàåçêëèïîìÄÅ"
    "ÉæÆôöòûùÿÖÜ¢£¥₧ƒ"
    "áíóúñÑªº¿⌐¬½¼¡«»"
    "░▒▓│┤╡╢╖╕╣║╗╝╜╛┐"
    "└┴┬├─┼╞╟╚╔╩╦╠═╬╧"
    "╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀"
    "αßΓπΣσµτΦΘΩδ∞φε∩"
    "≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ "
)


def fingerprint(img: Image.Image, x: int, y: int, cw: int, ch: int) -> int:
    px = img.load()
    bits = 0
    sx_step = max(1, cw // 8)
    sy_step = max(1, ch // 8)
    bit = 1
    for j in range(8):
        sy = y + min(ch - 1, j * sy_step)
        for i in range(8):
            sx = x + min(cw - 1, i * sx_step)
            r, g, b = px[sx, sy][:3]
            if (r + g + b) // 3 > 80:
                bits |= bit
            bit <<= 1
    return bits


def find_font(cell_h: int):
    """Find a usable monospace font, prefer DejaVu / Liberation Mono."""
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
        "/usr/share/fonts/truetype/freefont/FreeMono.ttf",
    ]
    for path in candidates:
        if Path(path).exists():
            return ImageFont.truetype(path, cell_h - 2)
    return ImageFont.load_default()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(Path(__file__).parent / "fontmap.py"))
    ap.add_argument("--cell", default="8x16")
    args = ap.parse_args()
    cw, ch = (int(x) for x in args.cell.split("x"))

    font = find_font(ch)
    fmap: dict[int, str] = {}

    for code in range(256):
        ch_str = CP437_TO_UNI[code]
        # Many CP437 glyphs aren't drawable with DejaVu Mono; for those we
        # fall back to a blank cell which matches CP437 spaces. The decoder
        # will emit '?' for unknown fingerprints.
        if not ch_str.strip() and code not in (0, 0xFF):
            continue

        img = Image.new("RGB", (cw, ch), (0, 0, 0))
        d = ImageDraw.Draw(img)
        try:
            d.text((0, 0), ch_str, fill=(255, 255, 255), font=font)
        except Exception:
            continue
        fp = fingerprint(img, 0, 0, cw, ch)
        if fp == 0:
            continue
        # Collisions: prefer the first ASCII-printable hit (32–126)
        if fp in fmap:
            existing = fmap[fp]
            if not (32 <= ord(existing[0]) < 127):
                fmap[fp] = ch_str
        else:
            fmap[fp] = ch_str

    out = ["# Auto-generated by build-fontmap.py — do not edit by hand.",
           f"# cell {cw}x{ch}, {len(fmap)} entries",
           "FINGERPRINTS = {"]
    for fp, ch_str in sorted(fmap.items()):
        out.append(f"    0x{fp:016x}: {ch_str!r},")
    out.append("}")
    Path(args.out).write_text("\n".join(out) + "\n")
    print(f"wrote {args.out} ({len(fmap)} entries)")


if __name__ == "__main__":
    main()
